# Generated by Django 2.2.5 on 2019-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_code',
        ),
    ]
