# Generated by Django 2.2.5 on 2019-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0003_brand_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.IntegerField(verbose_name='Brand Code'),
        ),
    ]
